[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.41" }
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }


[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server"]
